title: "JavaのビルドとCIのキホン"
summary: "この本は、Javaを書き始めた方が自分でビルドスクリプトを作成できるようになり、CIを使った継続的な開発を行えるようになることを目的としています。"
topics: ["java", "build", "gradle", "ci", "githubactions"]
published: true
price: 0

chapters:
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
